# Generated by Django 5.0.3 on 2024-03-28 21:18

from django.db import migrations, models

import user_info.validators


class Migration(migrations.Migration):
    dependencies = [
        ("user_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="birth_date",
            field=models.DateField(
                help_text="Birthdate as day/month/year", validators=[user_info.validators.validate_birth_date]
            ),
        ),
    ]
