# Generated by Django 5.0.2 on 2024-02-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('user_info', '0003_usertrackinglabel'), ('user_info', '0004_usertrackinglabel_description')]

    dependencies = [
        ('user_info', '0002_alter_usertrackingpoint_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrackingLabel',
            fields=[
                ('label', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=144)),
            ],
        ),
    ]
