# Generated by Django 5.0.2 on 2024-02-20 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_usertrackinglabel_squashed_0004_usertrackinglabel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrackingpoint',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.usertrackinglabel'),
        ),
    ]
