# Generated by Django 5.0.2 on 2024-02-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_alter_usertrackingpoint_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userannotation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertrackingpoint',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
