# Generated by Django 5.0.2 on 2024-02-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_rename_user_id_userannotation_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userannotation',
            old_name='user',
            new_name='user_info',
        ),
        migrations.RenameField(
            model_name='usertrackingpoint',
            old_name='user',
            new_name='user_info',
        ),
    ]
