# Generated by Django 5.0.2 on 2024-02-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0008_bearertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BearerToken',
        ),
    ]
